### PR TITLE
1 fix animation when child layout changes

### LINKED ISSUE #1: Wrong layout behavoir on content size change
When the content of the model changes it's size, it takes the modal CHILD_ANIM_DURATION ms to start and again LAYOUT_ANIM_DURATION ms to finish changing the size of the modal. I think the model should, in this case, not wait CHILD_ANIM_DURATION before changing it's size.

    <Animated.View
      style={styles.modalView}
      layout={Layout.delay(CHILD_ANIM_DURATION).duration(
        LAYOUT_ANIM_DURATION,
      )}>

### PR DESCRIPTION
**Pull request by susonthapa**
Added `disableLayoutChangeAnimation` to disable the layout animation once the view is mounted.

### With layout animation disabled
https://github.com/susonthapa/react-native-global-modal/assets/33973551/1eb00356-3953-4e75-98f6-58fe4952dc9e

### Removed delay when layout animations are enabled
https://github.com/susonthapa/react-native-global-modal/assets/33973551/7acc944e-0db3-4459-a6c4-266800c29809

Should Fix #1

### CODE REVIEW

File: src/Modal/GlobalModal.tsx [hunk 1]
```diff
@@ -22,6 +23,21 @@ export function hideGlobalModal(key: string) {
   DeviceEventEmitter.emit(HIDE_GLOBAL_MODAL, key)
 }
 
+const layoutAnimation = new Layout().delay(CHILD_ANIM_DURATION)
+  .duration(LAYOUT_ANIM_DURATION)
+  .build()
+
+// Using duration of 1ms to disable the animation(sort of)
+const disabledLayoutAnimation = new Layout().duration(1).build()
```
Comment (JaRoMasterDev) [inline src/Modal/GlobalModal.tsx]: A duration of -1 should finx the issue discrussed in #1

Comment (susonthapa) [reply src/Modal/GlobalModal.tsx]: Awesome, I have added that. I didn't get a chance to test this. Didn't know we had to pass -1 to disable the animation, good finding on that.
